resources:
- name: config
  type: git
  source:
    private_key: ((configuration.private_key))
    uri: ((configuration-uri))
    branch: master
    depth: 1
    paths: 
      - environments/sandbox/config/*
      - environments/sandbox/vars/*
- name: state
  type: git
  source:
    private_key: ((configuration.private_key))
    uri: ((configuration-uri))
    branch: master
    submodules: all
    depth: 1

- name: platform-automation-tasks
  type: s3
  source:
    access_key_id: ((aws_access_key))
    bucket: ((pivnet_products_bucket))
    region_name: ((region))
    secret_access_key: ((aws_secret_key))
    regexp: platform-automation-tasks-(.*).zip

- name: platform-automation-image
  type: s3
  source:
    access_key_id: ((aws_access_key))
    bucket: ((pivnet_products_bucket))
    region_name: ((region))
    secret_access_key: ((aws_secret_key))
    regexp: platform-automation-image-(.*).tgz

- name: opsman-product
  type: s3
  source:
    access_key_id: ((aws_access_key))
    bucket: ((pivnet_products_bucket))
    region_name: ((region))
    secret_access_key: ((aws_secret_key))
    regexp: ops-manager-aws-(.*)\.yml  

    #  - name: pas-product
    #    type: s3
    #    source:
    #      access_key_id: ((aws_access_key))
    #      bucket: ((pivnet_products_bucket))
    #      region_name: ((region))
    #      secret_access_key: ((aws_secret_key))
    #      regexp: cf-(.*)\.pivotal  

      #  - name: pas-stemcell
      #    type: s3
      #    source:
      #      access_key_id: ((aws_access_key))
      #      bucket: ((pivnet_products_bucket))
      #      region_name: ((region))
      #      secret_access_key: ((aws_secret_key))
      #      regexp: pas-stemcell/light-bosh-stemcell-.*-aws.*\.tgz

- name: one-time-trigger
  type: time
  source:
    interval: 999999h

interpolate-creds: &interpolate-creds
  image: platform-automation-image
  file: platform-automation-tasks/tasks/credhub-interpolate.yml
  params:
    CREDHUB_CLIENT: ((credhub-client))
    CREDHUB_SECRET: ((credhub-secret))
    CREDHUB_SERVER: ((credhub-server))
    CREDHUB_CA_CERT: ((credhub-ca-cert.certificate))
    PREFIX: '/concourse/main'
    INTERPOLATION_PATHS: environments/sandbox/config environments/sandbox/env
    SKIP_MISSING: true
  input_mapping:
    files: config
  output_mapping:
    interpolated-files: interpolated-creds

jobs:
  - name: install-opsman
    serial: true
    serial_groups: [ install ]
    plan:
      - aggregate:
        - get: platform-automation-image
          params:
            unpack: true
        - get: one-time-trigger
          trigger: true
        - get: platform-automation-tasks
          params:
            unpack: true
        - get: config
          trigger: true 
        - get: state
        - get: opsman-product
      - task: interpolate-creds
        <<: *interpolate-creds
      - task: create-vm
        image: platform-automation-image
        file: platform-automation-tasks/tasks/create-vm.yml
        input_mapping:
          image: opsman-product
          state: state
          config: interpolated-creds
          vars: config
        params:
          VARS_FILES: vars/environments/sandbox/vars/opsman-vars.yml
          STATE_FILE: environments/sandbox/state/state.yml
          OPSMAN_CONFIG_FILE: environments/sandbox/config/opsman.yml
        ensure: &make-state-commit
          do:
            - task: make-commit
              image: platform-automation-image
              file: platform-automation-tasks/tasks/make-git-commit.yml
              input_mapping:
                repository: config
                file-source: generated-state
              output_mapping:
                repository-commit: state-commit
              params:
                FILE_SOURCE_PATH: state.yml
                FILE_DESTINATION_PATH: environments/sandbox/state/state.yml
                GIT_AUTHOR_EMAIL: "pcf-pipeline-bot@example.com"
                GIT_AUTHOR_NAME: "Platform Automation Bot"
                COMMIT_MESSAGE: 'Update state file'
            - put: state
              params:
                repository: state-commit
                merge: true
      - task: configure-authentication
        image: platform-automation-image
        file: platform-automation-tasks/tasks/configure-authentication.yml
        attempts: 10
        input_mapping:
          env: interpolated-creds
          config: interpolated-creds
        params:
          ENV_FILE: environments/sandbox/env/env.yml
          AUTH_CONFIG_FILE: environments/sandbox/config/auth.yml
      - task: configure-director
        image: platform-automation-image
        file: platform-automation-tasks/tasks/configure-director.yml
        input_mapping:
          config: interpolated-creds
          env: interpolated-creds
          vars: config
        params:
          VARS_FILES: vars/environments/sandbox/vars/director-vars.yml
          ENV_FILE: environments/sandbox/env/env.yml
          DIRECTOR_CONFIG_FILE: environments/sandbox/config/director.yml
      - task: apply-director-changes
        image: platform-automation-image
        file: platform-automation-tasks/tasks/apply-director-changes.yml
        input_mapping:
          env: interpolated-creds
        params:
          ENV_FILE: environments/sandbox/env/env.yml
