---
opsman-configuration:
  aws:
    region: us-west-2
    vm_name: ops-manager-vm 
    boot_disk_size: 100 
    vpc_subnet_id: subnet-0ddfc4784df8ba08e 
    security_group_id: sg-064872eef5a2c3459
    key_pair_name: sandbox-ops-manager-key 
    iam_instance_profile_name: cp-ops-manager 
    instance_type: m5.large
    public_ip: 52.41.14.106
    use_instance_profile: true 
